# Dostosuj gałąź w workflow.rules, jeśli używasz innej niż main
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"

variables:
  NODE_IMAGE: node:22-bookworm
  NPM_CONFIG_CACHE: $CI_PROJECT_DIR/.npm
  NPM_CONFIG_FUND: "false"
  NPM_CONFIG_AUDIT: "false"

stages:
  - test

.cache_root: &cache_root
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/

web:build:
  image: $NODE_IMAGE
  stage: test
  <<: *cache_root
  script:
    - npm ci
    - npm run build -w web

api:test:
  image: $NODE_IMAGE
  stage: test
  <<: *cache_root
  script:
    - npm ci
    - npm run build -w api
    - npm run test -w api
